[versions]
agp = "8.10.1"

android-minSdk = "21"
android-compileSdk = "35"
android-buildToolsVersion = "35.0.0"

androidx-appcompat = "1.7.1"

kotlin = "2.2.0"

lib-version = "1.0.0"

compose-version = "1.8.3"
[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }

compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-version" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "compose-version" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-version" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-version" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-version" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }